version: "3.9"

services:
  postgres:
    image: postgres:18.1
    container_name: ledgerpoc-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ledgerpoc
      POSTGRES_USER: ledgerpoc
      POSTGRES_PASSWORD: ledgerpoc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledgerpoc -d ledgerpoc"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: